name: Build APK

on:
  push:
    branches:
      - master  # يمكن تغييرها إلى `main` إذا كانت هي الفرع الرئيسي
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # الخطوة 1: Checkout الكود من المستودع
      - name: Checkout code
        uses: actions/checkout@v2

      # الخطوة 2: إعداد JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'

      # الخطوة 3: إعداد Android SDK
      - name: Set up Android SDK
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          arch: x86_64
          force-avd-creation: true
          avd-name: test-avd

      # الخطوة 4: بناء التطبيق باستخدام Gradle
      - name: Build APK
        run: ./gradlew assembleRelease

      # الخطوة 5: رفع APK إلى GitHub (اختياري)
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk
